config/routes.rb
Ministers2::Application.routes.draw do
  get "ministers/index"
  resources :ministers, only: [:index, :show]
  root 'static_pages#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/minister.rb
class Minister < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ministers_controller.rb
class MinistersController < ApplicationController
  def index
    @ministers = Minister.all
  end

  def show
    @minister = Minister.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "日本の総理大臣"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def my_blog_path
    "http://www.succi.jp/blog/"
  end

  def facebook_script_tag
    snippet = <<EOF
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
EOF
    snippet.html_safe
  end

  def facebook_button_tag
    snippet = <<EOF
<div class="fb-like" data-href="http://nippon-no-souridaijin.herokuapp.com/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
EOF
    snippet.html_safe
  end

  def hatena_bookmark_button_tag
    snippet = <<EOF
<a href="http://b.hatena.ne.jp/entry/http://nippon-no-souridaijin.herokuapp.com/" class="hatena-bookmark-button" data-hatena-bookmark-title="日本の総理大臣" data-hatena-bookmark-layout="standard-balloon" data-hatena-bookmark-lang="ja" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only@2x.png" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a><script type="text/javascript" src="http://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script>
EOF
    snippet.html_safe
  end

  def twitter_button_tag
    snippet = <<EOF
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://nippon-no-souridaijin.herokuapp.com/">Tweet</a>
<script src="//platform.twitter.com/widgets.js"></script>
EOF
    snippet.html_safe
  end
end

app/helpers/ministers_helper.rb
module MinistersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/layouts/_footer.html.erb
<div class="container">
  <p>
    Copyright &copy; <%= link_to 'prime factor', my_blog_path %>,
    2014 All Rights Reserved.
  </p>
  <ul id="social-buttons">
    <li><%= hatena_bookmark_button_tag %></li>
    <li><%= twitter_button_tag %></li>
  </ul>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '日本の総理大臣', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "総理大臣一覧", ministers_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ministers2" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <%= render 'layouts/messages' %>
    <%= yield %>

    <footer class="site-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/ministers/index.html.erb
<% provide(:title, '総理大臣一覧') %>
<div class="container" id="pagetop">
  <section class="main">
    <div class="page-header">
      <h1>歴代内閣総理大臣の一覧</h1>
    </div>

    <table class="table table-bordered table-striped">
      <tr>
        <th>歴代</th>
        <th>氏名</th>
        <th>在職期間</th>
        <th>在職日数</th>
        <th>就任時年齢</th>
        <th>詳細</th>
      </tr>
      <% @ministers.each do |minister| %>
        <tr>
          <td><%= minister.successive %></td>
          <td><%= minister.name %></td>
          <td><%= minister.tenure %></td>
          <td><%= minister.days %></td>
          <td><%= minister.age %></td>
          <td>
            <%= link_to '詳細', minister_path(minister.id), class: 'btn btn-info btn-xs'  %>
          </td>
        </tr>
      <% end %>
    </table>

    <%= link_to '先頭へ戻る', '#pagetop', class: 'btn btn-warning btn-lg', id: 'return-to-top' %>
  </section>
</div>

app/views/ministers/show.html.erb
<% provide(:title, @minister.name) %>

<div class="container">
  <section class="main row">
    <aside class="col-md-3">
    </aside>
    <article class="col-md-9">
      <div class="page-header">
        <h1>
          <%= @minister.name %>
          <small>第<%= @minister.successive %>代 内閣総理大臣</small>
        </h1>
      </div>
      <div class="profile row">
        <div class="col-md-6">
          <%= image_tag "ministers/#{@minister.successive}.jpg", alt: 'portrait',
            size: '300x370', class: 'img-thumbnail' %>
        </div>
        <div class="col-md-6">
          <dl>
            <dt>在職期間</dt>
            <dd><%= @minister.tenure %></dd>
            <dt>在職日数</dt>
            <dd><%= @minister.days %></dd>
            <dt>就任時年齢</dd>
            <dd><%= @minister.age %></dd>
            <dt>生年月日</dt>
            <dd><%= @minister.birthdate %></dd>
            <dt>死去年月日</dt>
            <dd><%= @minister.deathdate %></dd>
            <dt>出身地</dt>
            <dd><%= @minister.birthplace %></dd>
          </dl>
        </div>
      </div>
      <footer class="article-footer">
        <%= link_to '一覧に戻る', ministers_path, class: 'btn btn-default' %>
      </footer>
    </article>
  </section>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="container">
  <section class="main row">
    <aside class="col-xs-3">
    </aside>
    <article class="col-xs-9">
      <div class="page-header">
        <h1>このサイトについて</h1>
      </div>

      <h3>公開している情報</h3>
      <p>
        このサイトでは日本の歴代内閣総理大臣の一覧と、それぞれの総理大臣の概要情報を公開しています。記載している情報は<a href="http://www.kantei.go.jp/">首相官邸ホームページ</a>の「<a href="http://www.kantei.go.jp/jp/rekidai/index.html">内閣制度と歴代内閣</a>」を元にしています。
      </p>

      <h3>サイト作成の目的</h3>
      <p>
        このサイトは、作成者が<a href="http://rubyonrails.org/">Ruby on Rails</a>を利用したウェブサイトシステム開発の学習を目的に作成したものです。記載されいている情報の正確性は保証いたしませんのでご注意ください。正しい情報を確認したい方は、上記の<a href="http://www.kantei.go.jp/">首相官邸ホームページ</a>をご確認いただくようお願いします。
      </p>
    </article>
  </section>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="container">
  <section class="main row">
    <aside class="col-xs-3">
    </aside>
    <article class="col-xs-9">
      <div class="page-header">
        <h1>お問い合わせ</h1>
      </div>

      <h3>連絡先</h3>

      <p>
        お問い合わせにつきましては、下記のTwitterアカウント宛てにメッセージをいただくか、ブログのコンタクトフォームよりご連絡をいただくようお願いいたします。
      </p>

      <dl>
        <dt><i class="fa fa-twitter"></i> Twitter</dt>
        <dd><%= link_to('@succi0303', 'https://twitter.com/succi0303')%></dd>
        <dt><i class="fa fa-rss-square"></i> Blog</dt>
        <dd><%= link_to('prime factor', 'http://www.succi.jp/blog/') %></dd>
      </dl>

      <h3>ソースコード</h3>

      <p>
        本ウェブサイトのソースコードはGithubにて公開しています。ご興味を持たれた方は下記のGithubリポジトリをご参照ください。
      </p>

      <dl>
        <dt><i class="fa fa-github"></i> Github</dt>
        <dd><%= link_to('succi0303/ministers2', 'https://github.com/succi0303/ministers2') %></dd>
      </dl>

    </article>
  </section>
</div>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>日本の総理大臣</h1>
    <p>このページでは日本の歴代総理大臣の情報を紹介しています。</p>
    <%= link_to '一覧を見る »', ministers_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>